### ISSUE TITLE
Oversampling may not be treating the PSF correctly

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#130]
I'm finding the oversampled PSF images to be much more centrally peaked than the non-oversampled images.  Attached is a postage stamp of 2 F087 images with identical input catalogs, but oversample of 1 on the left and 10 on the right.  The oversample of 1 clearly has much less flux in the central pixel.
<img width="815" alt="Zoom_image_example_OS1_OS10" src="https://user-images.githubusercontent.com/8866546/119871099-f9e8e280-bed6-11eb-9c56-413474b81552.png">

**Comment by benw1** [comment]
In addition, I am finding that when I add the same star with oversample=10 and oversample=1, the oversample=10 star will have ~10% more counts than the oversample=1 star. There appears to be some bug in the oversample routine...

**Comment by benw1** [comment]
Is there any timeline of being able to check on this?  It makes performing tests on PSF effects and crowding not yet possible with STIPS.  Thanks for any response.

**Comment by york-stsci** [comment]
I'm sorry about the delayed reply. You ran into a combination of other projects needing my time, staff changes on STIPS, and a vacation.

If there is a problem with the oversampled PSF, that problem is happening in webbpsf rather than in STIPS. Because STIPS does not have the ability to generate PSFs other than by using webbpsf, it will have to be solved by them.

STIPS does not have an oversample routine. Instead, it creates a data array at a pixel scale based on the WFI pixel scale and the chosen oversample, adds counts to the array, and then uses a numpy sum-and-reshape to bin the data during the error adding routines. Stars are added as point sources directly, and then psf-convolved. So if there are count-rate-within-a-radius issues, they are probably more a result of oversample-1 not accurately representing sub-pixel position (and the oversample-1 PSF being more of an approximation) than anything else.

**Comment by york-stsci** [comment]
Also as a quick note, Robel is actually going off to be a PhD student, and so he is no longer working on STIPS.

And finally, I'm sorry I can't be more help with this right now, but I can't actually figure out what might be going on inside the STIPS code to cause these issues.

**Comment by benw1** [comment]
I'm not positive the issue is with WebbPSF.  The oversample 1 and 10 PSFs in the PSF files look like they may be consistent, but the oversample 1 PSF in the STIPS image looks like it may be different from the one in the file.   In the attached screenshot the upper 2 panels are the PSF files for oversample 10 and 1, and the lower two are the resulting STIPS images.  To my eye, the STIPS image for the oversample 1 case looks a bit different from the PSF file, while in the oversample 10 case, the PSF file and STIPS image look basically consistent.
<img width="855" alt="Screen Shot 2021-06-18 at 3 53 01 PM" src="https://user-images.githubusercontent.com/8866546/122834399-5efbe200-d2a3-11eb-9cfd-01465936e2f2.png">

**Comment by york-stsci** [comment]
The only thing that I can think of here is whether there's an interaction of some sort with the PSF grid. The PSF convolution is done by splitting the image into regions, and generating a PSF from the grid at the centre of each region. I don't know what's happening in the case of your reductions, but if you have logging on then it should give you some information about how many regions the image is being divided into, which will in turn give you an idea of whether the difference you're seeing has anything to do with that.

**Comment by benw1** [comment]
Are you referring to the PSF grid?  If so, these tests were all done without gridding.  For example, the name of the PSF files were psf_WFI_1.0.8_F087_1_1_sca01.fits and psf_WFI_1.0.8_F087_10_1_sca01.fits.  I'll take a look at the logging too, but thought I'd share that in case it helps.

**Comment by york-stsci** [comment]
Okay, so you're using a 1x1 PSF grid (STIPS does not have the ability to use a non-gridded PSF). I don't know what happens when you ask for a PSF image from a 1x1 grid at various different detector locations.

**Comment by benw1** [comment]
Ok, I'll try using a grid to see if that helps, but something appears to go off the rails when using a 1x1 grid with oversample of 1.  Things seem better with a 1x1 grid with higher oversample rates, but I haven't tested in detail yet.

**Comment by benw1** [comment]
When I use the grid 5x5 option, the image turns out essentially identical to the grid 1x1 option, and does not look much like the psf file.  In the attached image, the left is the 1x1 grid, and the right is the 5x5 grid, zoomed in on a single star in the center.
<img width="817" alt="Screen Shot 2021-06-24 at 12 12 41 PM" src="https://user-images.githubusercontent.com/8866546/123319808-c608d900-d4e5-11eb-860a-b1bd9e3f06c6.png">

**Comment by york-stsci** [comment]
What is the PSF file that you're comparing with?

Also, I have run across information that there might be webbpsf issues with the way PSFs are calculated/computed that are oversample-dependent (this is based on an aside in a meeting so I don't have any sort of details yet).

Also, if it turns out that this is an issue with oversample=1 in particular, or with a 1x1 grid in particular (or both), then unless it's an easy fix I'm unlikely to put substantial effort into it, simply because STIPS is not really designed to work at that oversample level anyway, and there are much more significant issues in STIPS at that oversample.

**Comment by benw1** [comment]
I'm comparing with the file that gets produced in the psf_cache/  directory when I run STIPS.  I agree that the oversample=1 level is not particularly useful in the long run, but it runs the fastest, so it is very useful for very simple tests like the one I'm running, which is testing oversample=1 PSF fitting photometry with oversample=1 STIPS images.  Because I can't get that to work yet, I haven't proceeded to test photometry with higher oversample settings, and I don't know if this problem is happening for other oversample settings.

**Comment by york-stsci** [comment]
Okay. So you're using the python psf.evaluate() at the centre of the detector to make the comparison image?

**Comment by benw1** [comment]
I am opening the psf_WFI_1.0.8_F087_1_1_sca01.fits file in ds9 to make the comparison image.

**Comment by york-stsci** [comment]
Okay. So what would a fix look like? Is there something other than generating a PSF (or using a cached PSF) of the same oversample as the image, and convolving the image with that PSF (potentially broken into image segments depending on image and PSF size) that would solve the issue?

**Comment by benw1** [comment]
Let me check with my PSF expert to see if there is another way.  I'm not sure why that process would cause the stars to look so different from PSF the oversample=1 images.  Stay tuned...

**Comment by york-stsci** [comment]
If possible, can you do a re-test with a clone of the most recent STIPS repository? I've made additional changes to include Pandeia 1.6 and (mostly) update the testing infrastructure, but in so doing it also means that the version you can clone now is definitely the same as the version I've been looking at and testing locally, so even if only for my own peace of mind, it would help if you can make another check.

**Comment by york-stsci** [comment]
Superseded by version 2.
