### ISSUE TITLE
Source Position issue

### ISSUE THREAD

**Issue by Russell-Ryan** [spacetelescope/STScI-STIPS#134]
It appears that the precise source positions in the input catalogs do not match up with sources once rendered as an image.  They appear to be off by ~2 pixel.  I've attached a screenshot showing the discrepancy.  
<img width="1577" alt="Screen Shot 2021-07-22 at 4 09 14 PM" src="https://user-images.githubusercontent.com/9220272/126704427-abf0bfc5-2b64-4e73-bd9a-8c9c6add3e9a.png">
<img width="1577" alt="Screen Shot 2021-07-22 at 4 08 46 PM" src="https://user-images.githubusercontent.com/9220272/126704434-10eb5f40-4d8f-46f2-ab26-914183b6b054.png">

I created these images by following the notebook: "STIPS Tutorial.ipynb". I loaded the stellar catalog that this notebook makes  and made circular regions at those coordinates.

**Comment by Russell-Ryan** [comment]
I've redone this test, but with a "mixed catalog", where I have created an image centered at (RA,Dec)=(0,0) with 11 equally-spaced point sources along the Dec axis.  I've attached the script, which also generates a ds9 region file to highlight the positional offsets.

[example.py.txt](https://github.com/spacetelescope/STScI-STIPS/files/6886741/example.py.txt)

**Comment by york-stsci** [comment]
After a quick check, it appears that this issue may be unique to images with oversample=1. Can you try running your script again, but when you create the ObservationModule pass in the keyword oversample=N, where N>1, and let me know if you see the same offset?

**Comment by york-stsci** [comment]
Oversample=1
<img width="1092" alt="oversample1" src="https://user-images.githubusercontent.com/5478756/127714611-bfc7a1ef-c049-485e-98be-1778f8ae36bb.png">

Oversample=3
<img width="1092" alt="oversample3" src="https://user-images.githubusercontent.com/5478756/127714638-c6aa98bf-e42b-4e55-9c02-2d22f60d91ba.png">

Oversample=5
<img width="1092" alt="oversample5" src="https://user-images.githubusercontent.com/5478756/127714650-44c91cda-4953-4da5-9aa7-c12c4accf2d2.png">

**Comment by york-stsci** [comment]
Okay, and now I think I've figured things out even for oversample=1 for any systematic offset. The problem was that when I was calling the astropy wcs world2pix function, I was feeding in an origin of 1 (which is appropriate for FITS files, which are in turn the ultimate output format) as opposed to 0 (appropriate for numpy arrays, which are the intermediate holding format). The image below has three frames.

Left is oversample=1, origin=1. Middle is overample=1, origin=0. Right is oversample=3, origin=0.

<img width="1583" alt="Screen Shot 2021-08-02 at 11 28 30 AM" src="https://user-images.githubusercontent.com/5478756/127886399-9882999b-5a89-4a98-bb6a-76e330bc16b1.png">

**Comment by york-stsci** [comment]
This is effectively part of version 2 at this point, and is being tracked separately in #142
