### ISSUE TITLE
STIPS Version 2 issue discussion

### ISSUE THREAD

**Issue by york-stsci** [spacetelescope/STScI-STIPS#152]
@Russell-Ryan @benw1 @jrhastro 

This is a holding thread for this that we might want to consider changing or re-thinking for STIPS version 2 (because it's not often that there's a chance to make potentially non-backwards-compatible changes). Things like changing STIPS output from providing counts to rates (counts/s), changing what sources of residual error STIPS can add, changing how those sources are calculated/derived, or anything else you can think of.

This issue isn't for discussion of how/when to implement specific changes, but is rather a place to put changes that you might like to see so that we can have a discussion about whether making that change makes sense. Please feel free to add or tag anyone else whom you think should be involved in this discussion.

**Comment by jrhastro** [comment]
Thanks for starting the discussion @york-stsci.  From my perspective, I would like to see us prioritize bugs/changes that focus on supporting the upcoming ROSES call.  For example, what changes do we need to make to get to a version we are comfortable widely advertising to the community?  Or, what changes/issues should we prioritize because they are extremely important to the community's data simulation efforts?

@benw1 @Russell-Ryan What do you think?
