### ISSUE TITLE
WCS header keywords are mixed up

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#39]
We have had trouble mosaicking the STIPS output because montage cannot make sense of the headers.  We asked the montage developers for help, and here is their response:

There are three ways to specify the rotation/scale information.  The two can
be combined into one matrix (CD1_1 through CD2_2) or the rotation matrix
can be given as PC1_1 through PC2_2 and the pixel scale as CDELT1/CDELT2.
The third way is to give CDELT1/CDELT2 and a rotation angle as CROTA2.

What you've got here looks like the second but the values of the PC matrix are
actually what should be in a CD matrix and the CDELT value are nonsensical
(1x1 degree pixels).

**Comment by benw1** [comment]
Here are the adjustments that need to be made to the headers.  STIPS should be edited to produce headers with these changes so that they do not need to be made by the user.

fname, extension = os.path.splitext(file)
fits.delval(file, 'CDELT1')
fits.delval(file, 'CDELT2')
pc1_1 = fits.getval(file, 'PC1_1')
pc1_2 = fits.getval(file, 'PC1_2')
pc2_1 = fits.getval(file, 'PC2_1')
pc2_2 = fits.getval(file, 'PC2_2')
fits.setval(file, 'CD2_2', value=pc2_2, after='CRPIX2')
fits.setval(file, 'CD2_1', value=pc2_1, after='CRPIX2')
fits.setval(file, 'CD1_2', value=pc1_2, after='CRPIX2')
fits.setval(file, 'CD1_1', value=pc1_1, after='CRPIX2')
fits.delval(file, 'PC1_1')
fits.delval(file, 'PC1_2')
fits.delval(file, 'PC2_1')
fits.delval(file, 'PC2_2')

**Comment by york-stsci** [comment]
The file WCS is being generated directly by calling astropy's wcs.to_header() function. As such, the bug should be filed against astropy not against stips.

**Comment by benw1** [comment]
OK. I have put in a bug report on the astropy github page.

**Comment by york-stsci** [comment]
So, in particular, what's happening is that STIPS currently builds its WCS by creating a CD matrix, and if you do that astropy then takes that data, but internally copies the CD matrix you gave it and calls it a PC matrix. Then, since astropy will not let you produce a FITS header with anything but a PC matrix, and since the CD matrix you gave it already includes scaling, it sets CDELT to 1.0 and just uses the CD matrix as its PC matrix.

I think, based on testing with the current astropy, that I should be able to build the STIPS WCS using a PC matrix and CDELT keyword in the first place, and if I do that then the WCS header information should be reasonable. I'm currently working on a change to test that, and I'll let you know where to look for it to see if it solves your problem (there's still a bug in astropy, and it still needs to be fixed, because if you accept the user building a WCS with a CD matrix, but you only support turning it into a FITS header with a PC matrix, you *need* to transform the CD matrix internally).

**Comment by benw1** [comment]
Here is the response from the astropy developers:
If you have to use a CD matrix in general code you may detect that a CD matrix was in the input using wcs.wcs.has_cd() and rename the keywords. Currently there's no function in astropy that would do this, although there was discussion in the past about it. I have to find it to remind myself about all the arguments.
